# Site settings
title: "Joe Francis | Portfolio"
email: francisjoe238@gmail.com
description: "Electrical Engineering Student at KMITL"
url: "https://jo-francis.github.io" # ใส่ URL ของคุณ
baseurl: "" 
github_username: joefrann
minimal_mistakes_skin: air # ลองเปลี่ยนเป็น air, aqua, contrast, dark, dirt, neon ได้
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
include:
  - _pages

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Author Settings (ส่วนที่จะโชว์ด้านซ้ายของเว็บ)
author:
  name    : "Joe Francis"
  avatar  : "/assets/images/bio-photo.jpg" # เอารูปไปวางในโฟลเดอร์นี้แล้วเปลี่ยนชื่อให้ตรงกัน
  bio     : "Electrical Engineering Student at KMITL | Freelance Instructor"
  location: "Bangkok, Thailand"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/joefrann"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/" # ใส่ลิงก์ IG ของคุณ

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/joefrann"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
